### ISSUE TITLE
Exception thrown when groovy intellisense requested for un-linked library

### ISSUE THREAD

**Issue by mrglassdanny** [mrglassdanny/moca-language-server#19]

**Comment by mrglassdanny** [comment]
![Uploading issue19.gif…]()

**Comment by mrglassdanny** [comment]
![issue19](https://user-images.githubusercontent.com/66927870/94383968-1eea4300-0107-11eb-9c85-456807ee5f44.gif)

**Comment by dglass-longbow** [comment]
Fixed issue by catching NoClassDefFoundError in necessary spots. Catching Errors is not considered best practice, but in this case I think it is okay.
![example](https://user-images.githubusercontent.com/36458190/95412189-01c72880-08ee-11eb-99c1-710725be1e45.gif)

**Comment by dglass-longbow** [comment]
Fix will be in next release!
