### ISSUE TITLE
Intellisense fails to work on subquery during "Syntax Error"

### ISSUE THREAD

**Issue by lukerhoffman** [mrglassdanny/moca-language-server#25]
```
[Select foo.bar,
        foo.wh
   from locmst loc
   join(select stoloc bar,
               wh_id
          from locmst
         where rownum < 10) foo
     on loc.stoloc = foo.bar
  where rownum < 10]
```

![image](https://user-images.githubusercontent.com/49175909/95244435-8f642480-07d7-11eb-82a0-100f7cbdb056.png)

![image](https://user-images.githubusercontent.com/49175909/95244348-73f91980-07d7-11eb-94f9-1265de81f8fa.png)

**Comment by dglass-longbow** [comment]
@lukerhoffman  -- found the issue for this. Basically I need do some preprocessing similar to groovy before completion items are generated. 

![example](https://user-images.githubusercontent.com/36458190/95387782-d7a64400-08b6-11eb-8b98-9634356b9d87.gif)

Fix for this will go out in next version!
