### ISSUE TITLE
MOCA Trace Outliner having issues on macOS

### ISSUE THREAD

**Issue by ghost** [mrglassdanny/moca-language-server#72]
Decorations fail to load, hover does not work, definition lookup does not work

**Comment by dglass-longbow** [comment]
Pretty sure I found the issue. It has to do with the name of the file. For instance, trace file name "FOOBAR%BAZ%" fails to load decorations, hover, and definition, while *normal* file names work fine.

**Comment by mrglassdanny** [comment]
After some more testing, it actually appears to be that mac encodes the request uri whereas windows does not. Therefore, the map's key in MocaServices will not match the mac request uri.

**Comment by mrglassdanny** [comment]
This has been added in 1.9.20
